version: "3.7"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  flask:
    build: .
    container_name: flask
    restart: always
    volumes:
      - ./logs/:/logs/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - LOG_FILE=./logs/logs.log
      - BACKEND_OBJECTIVES_DATA=../common/objectives/data
    ports:
      - "5000:5000"
    command: flask run --host 0.0.0.0
    depends_on:
      - worker

  gunicorn:
    build: .
    container_name: gunicorn
    restart: always
    volumes:
      - ./logs/:/logs/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - LOG_FILE=./logs/logs.log
      - BACKEND_OBJECTIVES_DATA=../common/objectives/data
    ports:
      - "8000:8000"
    command: gunicorn -w 4 -b 0.0.0.0:8000 routes:application
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    restart: always
    volumes:
      - ./logs/:/logs/
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - LOG_FILE=./logs/logs.log
      - BACKEND_OBJECTIVES_DATA=../common/objectives/data
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    ports:
      - "5555:5555"
    depends_on:
      - redis